#
#Tue May 26 16:57:25 EDT 2026
task-tag-projects-already-scanned=PADL Creator AspectJ,PADL Design Motifs,PADL Statements,PADL Creator C++ (ANTLR),PADL Creator ClassFile,POM,PADL Analyses,SAD,ArgoUML_0.28,PADL,PADL Statements Creator ClassFile,CPL,cfparse
